# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d26ea72a419b773f1a89b3bb9b22c126"
name = "nic-test-v2"
application_url = "https://frequencies-enlarge-jj-lightning.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nic-test-v1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_cart_transforms,read_checkout_branding_settings,read_checkouts,read_content,read_customer_events,read_customer_merge,read_customers,read_discounts,read_draft_orders,read_files,read_fulfillments,read_gift_cards,read_inventory,read_legal_policies,read_locales,read_locations,read_marketing_events,read_markets,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_order_edits,read_orders,read_payment_terms,read_price_rules,read_product_listings,read_products,read_publications,read_purchase_options,read_reports,read_resource_feedbacks,read_returns,read_script_tags,read_shipping,read_shopify_payments_disputes,read_shopify_payments_payouts,read_store_credit_account_transactions,read_store_credit_accounts,read_themes,read_third_party_fulfillment_orders,read_translations,read_validations,write_assigned_fulfillment_orders,write_cart_transforms,write_checkout_branding_settings,write_checkouts,write_content,write_customer_merge,write_customers,write_discounts,write_draft_orders,write_files,write_fulfillments,write_gift_cards,write_inventory,write_locales,write_marketing_events,write_markets,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_order_edits,write_orders,write_payment_terms,write_pixels,write_price_rules,write_products,write_publications,write_purchase_options,write_reports,write_resource_feedbacks,write_returns,write_script_tags,write_shipping,write_store_credit_account_transactions,write_themes,write_third_party_fulfillment_orders,write_translations,write_validations"

[auth]
redirect_urls = [
  "https://frequencies-enlarge-jj-lightning.trycloudflare.com/auth/callback",
  "https://frequencies-enlarge-jj-lightning.trycloudflare.com/auth/shopify/callback",
  "https://frequencies-enlarge-jj-lightning.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
